//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogVisitor
    {
        public int LogID { get; set; }
        public int VisitorID { get; set; }
        public int ContactID { get; set; }
        public int LocationID { get; set; }
        public int CompanyID { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedByUserID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Location Location { get; set; }
        public virtual Log Log { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
