//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int VisitID { get; set; }
        public Nullable<byte> VisitorNo { get; set; }
        public string Visitor1 { get; set; }
        public Nullable<int> SecuredAreaId { get; set; }
        public Nullable<int> TenantDepartmentId { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual VisitorLog VisitorLog { get; set; }
    }
}
