//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VisitorLogContext : DbContext
    {
        public VisitorLogContext()
            : base("name=VisitorLogContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<AssetHistory> AssetHistories { get; set; }
        public virtual DbSet<AssetType> AssetTypes { get; set; }
        public virtual DbSet<AssetTypeAsset> AssetTypeAssets { get; set; }
        public virtual DbSet<AssetTypeAssetHistory> AssetTypeAssetHistories { get; set; }
        public virtual DbSet<AssetTypeHistory> AssetTypeHistories { get; set; }
        public virtual DbSet<Badge> Badges { get; set; }
        public virtual DbSet<BadgeHistory> BadgeHistories { get; set; }
        public virtual DbSet<BadgeType> BadgeTypes { get; set; }
        public virtual DbSet<BadgeTypeBadge> BadgeTypeBadges { get; set; }
        public virtual DbSet<BadgeTypeBadgeHistory> BadgeTypeBadgeHistories { get; set; }
        public virtual DbSet<BadgeTypeHistory> BadgeTypeHistories { get; set; }
        public virtual DbSet<Campus> Campus1 { get; set; }
        public virtual DbSet<CampusHistory> CampusHistories { get; set; }
        public virtual DbSet<CampusLocation> CampusLocations { get; set; }
        public virtual DbSet<CampusLocationHistory> CampusLocationHistories { get; set; }
        public virtual DbSet<CampusStation> CampusStations { get; set; }
        public virtual DbSet<CampusStationHistory> CampusStationHistories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyHistory> CompanyHistories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationHistory> LocationHistories { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<LogVisit> LogVisits { get; set; }
        public virtual DbSet<LogVisitor> LogVisitors { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<StationHistory> StationHistories { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<VisitHistory> VisitHistories { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
        public virtual DbSet<VisitorHistory> VisitorHistories { get; set; }
    }
}
