//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitorLog()
        {
            this.VisitorFiles = new HashSet<VisitorFile>();
            this.VisitorLogAccessIDs = new HashSet<VisitorLogAccessID>();
            this.VisitorLogRoomIDs = new HashSet<VisitorLogRoomID>();
        }
    
        public int VisitID { get; set; }
        public string VisitorLogNo { get; set; }
        public string FY { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public Nullable<byte> Amendment { get; set; }
        public Nullable<System.DateTime> AmendDateTime { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<bool> OnGoing { get; set; }
        public string Company { get; set; }
        public byte CampusID { get; set; }
        public string OtherRoomInfo { get; set; }
        public string OtherAccessAreaInfo { get; set; }
        public Nullable<int> PrimaryContactId { get; set; }
        public Nullable<int> SecondaryContactId { get; set; }
        public string Reason { get; set; }
        public string SpecialInstruction { get; set; }
        public Nullable<int> SubmittedById { get; set; }
        public Nullable<int> DistributedById { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Testing { get; set; }
    
        public virtual Visitor Visitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorFile> VisitorFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorLogAccessID> VisitorLogAccessIDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorLogRoomID> VisitorLogRoomIDs { get; set; }
    }
}
