//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitHistory
    {
        public int ID { get; set; }
        public int VisitID { get; set; }
        public System.DateTime ScheduledCheckInTime { get; set; }
        public System.DateTime ScheduledCheckOutTime { get; set; }
        public Nullable<System.DateTime> ActualCheckInTime { get; set; }
        public Nullable<System.DateTime> ActualCheckOutTime { get; set; }
        public string ModifiedByUserID { get; set; }
        public string ModifiedDate { get; set; }
        public System.DateTime AuditDate { get; set; }
    }
}
