//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VisitorLogContext : DbContext
    {
        public VisitorLogContext()
            : base("name=VisitorLogContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessArea> AccessAreas { get; set; }
        public virtual DbSet<Campu> Campus { get; set; }
        public virtual DbSet<EmpRef> EmpRefs { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<SecuredArea> SecuredAreas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TenantDepartment> TenantDepartments { get; set; }
        public virtual DbSet<BadgeType> BadgeTypes { get; set; }
        public virtual DbSet<VisitorLog> VisitorLogs { get; set; }
        public virtual DbSet<EmployeeRole> EmployeeRoles { get; set; }
        public virtual DbSet<LogCounter> LogCounters { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
        public virtual DbSet<VisitorCheckInOut> VisitorCheckInOuts { get; set; }
        public virtual DbSet<VisitorDetail> VisitorDetails { get; set; }
        public virtual DbSet<VisitorFile> VisitorFiles { get; set; }
        public virtual DbSet<VisitorLogAccessID> VisitorLogAccessIDs { get; set; }
        public virtual DbSet<VisitorLogRoomID> VisitorLogRoomIDs { get; set; }
    }
}
