//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorLogRoomID
    {
        public int VisitID { get; set; }
        public short RoomID { get; set; }
        public string OtherRoom { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual VisitorLog VisitorLog { get; set; }
    }
}
