//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="Asset"/> and <see cref="AssetDTO"/>.
    /// </summary>
    static public partial class AssetMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="AssetDTO"/> converted from <see cref="Asset"/>.</param>
        static partial void OnDTO(this Asset entity, AssetDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Asset"/> converted from <see cref="AssetDTO"/>.</param>
        static partial void OnEntity(this AssetDTO dto, Asset entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="AssetDTO"/> to an instance of <see cref="Asset"/>.
        /// </summary>
        /// <param name="dto"><see cref="AssetDTO"/> to convert.</param>
        public static Asset ToEntity(this AssetDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new Asset();
                 
            entity.ID = dto.ID;     
            entity.Name = dto.Name;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreateDate = dto.CreateDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="Asset"/> to an instance of <see cref="AssetDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Asset"/> to convert.</param>
        public static AssetDTO ToDTO(this Asset entity)
        {
            if (entity == null) return null;
    
            var dto = new AssetDTO();
                 
            dto.ID = entity.ID;     
            dto.Name = entity.Name;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreateDate = entity.CreateDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="AssetDTO"/> to an instance of <see cref="Asset"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Asset> ToEntities(this IEnumerable<AssetDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="Asset"/> to an instance of <see cref="AssetDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<AssetDTO> ToDTOs(this IEnumerable<Asset> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
