//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="Badge"/> and <see cref="BadgeDTO"/>.
    /// </summary>
    static public partial class BadgeMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="BadgeDTO"/> converted from <see cref="Badge"/>.</param>
        static partial void OnDTO(this Badge entity, BadgeDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Badge"/> converted from <see cref="BadgeDTO"/>.</param>
        static partial void OnEntity(this BadgeDTO dto, Badge entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="BadgeDTO"/> to an instance of <see cref="Badge"/>.
        /// </summary>
        /// <param name="dto"><see cref="BadgeDTO"/> to convert.</param>
        public static Badge ToEntity(this BadgeDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new Badge();
                 
            entity.ID = dto.ID;     
            entity.Number = dto.Number;     
            entity.IsActive = dto.IsActive;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreatedDate = dto.CreatedDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="Badge"/> to an instance of <see cref="BadgeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Badge"/> to convert.</param>
        public static BadgeDTO ToDTO(this Badge entity)
        {
            if (entity == null) return null;
    
            var dto = new BadgeDTO();
                 
            dto.ID = entity.ID;     
            dto.Number = entity.Number;     
            dto.IsActive = entity.IsActive;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreatedDate = entity.CreatedDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="BadgeDTO"/> to an instance of <see cref="Badge"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Badge> ToEntities(this IEnumerable<BadgeDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="Badge"/> to an instance of <see cref="BadgeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<BadgeDTO> ToDTOs(this IEnumerable<Badge> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
