//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="BadgeTypeBadgeHistory"/> and <see cref="BadgeTypeBadgeHistoryDTO"/>.
    /// </summary>
    static public partial class BadgeTypeBadgeHistoryMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="BadgeTypeBadgeHistoryDTO"/> converted from <see cref="BadgeTypeBadgeHistory"/>.</param>
        static partial void OnDTO(this BadgeTypeBadgeHistory entity, BadgeTypeBadgeHistoryDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="BadgeTypeBadgeHistory"/> converted from <see cref="BadgeTypeBadgeHistoryDTO"/>.</param>
        static partial void OnEntity(this BadgeTypeBadgeHistoryDTO dto, BadgeTypeBadgeHistory entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="BadgeTypeBadgeHistoryDTO"/> to an instance of <see cref="BadgeTypeBadgeHistory"/>.
        /// </summary>
        /// <param name="dto"><see cref="BadgeTypeBadgeHistoryDTO"/> to convert.</param>
        public static BadgeTypeBadgeHistory ToEntity(this BadgeTypeBadgeHistoryDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new BadgeTypeBadgeHistory();
                 
            entity.ID = dto.ID;     
            entity.BadgeTypeID = dto.BadgeTypeID;     
            entity.BadgeID = dto.BadgeID;     
            entity.ModifedByUserID = dto.ModifedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;     
            entity.AuditDate = dto.AuditDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="BadgeTypeBadgeHistory"/> to an instance of <see cref="BadgeTypeBadgeHistoryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="BadgeTypeBadgeHistory"/> to convert.</param>
        public static BadgeTypeBadgeHistoryDTO ToDTO(this BadgeTypeBadgeHistory entity)
        {
            if (entity == null) return null;
    
            var dto = new BadgeTypeBadgeHistoryDTO();
                 
            dto.ID = entity.ID;     
            dto.BadgeTypeID = entity.BadgeTypeID;     
            dto.BadgeID = entity.BadgeID;     
            dto.ModifedByUserID = entity.ModifedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;     
            dto.AuditDate = entity.AuditDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="BadgeTypeBadgeHistoryDTO"/> to an instance of <see cref="BadgeTypeBadgeHistory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<BadgeTypeBadgeHistory> ToEntities(this IEnumerable<BadgeTypeBadgeHistoryDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="BadgeTypeBadgeHistory"/> to an instance of <see cref="BadgeTypeBadgeHistoryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<BadgeTypeBadgeHistoryDTO> ToDTOs(this IEnumerable<BadgeTypeBadgeHistory> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
