//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="BadgeTypeHistory"/> and <see cref="BadgeTypeHistoryDTO"/>.
    /// </summary>
    static public partial class BadgeTypeHistoryMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="BadgeTypeHistoryDTO"/> converted from <see cref="BadgeTypeHistory"/>.</param>
        static partial void OnDTO(this BadgeTypeHistory entity, BadgeTypeHistoryDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="BadgeTypeHistory"/> converted from <see cref="BadgeTypeHistoryDTO"/>.</param>
        static partial void OnEntity(this BadgeTypeHistoryDTO dto, BadgeTypeHistory entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="BadgeTypeHistoryDTO"/> to an instance of <see cref="BadgeTypeHistory"/>.
        /// </summary>
        /// <param name="dto"><see cref="BadgeTypeHistoryDTO"/> to convert.</param>
        public static BadgeTypeHistory ToEntity(this BadgeTypeHistoryDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new BadgeTypeHistory();
                 
            entity.ID = dto.ID;     
            entity.BadgeTypeID = dto.BadgeTypeID;     
            entity.Code = dto.Code;     
            entity.Name = dto.Name;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;     
            entity.AuditDate = dto.AuditDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="BadgeTypeHistory"/> to an instance of <see cref="BadgeTypeHistoryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="BadgeTypeHistory"/> to convert.</param>
        public static BadgeTypeHistoryDTO ToDTO(this BadgeTypeHistory entity)
        {
            if (entity == null) return null;
    
            var dto = new BadgeTypeHistoryDTO();
                 
            dto.ID = entity.ID;     
            dto.BadgeTypeID = entity.BadgeTypeID;     
            dto.Code = entity.Code;     
            dto.Name = entity.Name;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;     
            dto.AuditDate = entity.AuditDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="BadgeTypeHistoryDTO"/> to an instance of <see cref="BadgeTypeHistory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<BadgeTypeHistory> ToEntities(this IEnumerable<BadgeTypeHistoryDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="BadgeTypeHistory"/> to an instance of <see cref="BadgeTypeHistoryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<BadgeTypeHistoryDTO> ToDTOs(this IEnumerable<BadgeTypeHistory> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
