//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="BadgeType"/> and <see cref="BadgeTypeEntity"/>.
    /// </summary>
    static public partial class BadgeTypeMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="BadgeTypeEntity"/> converted from <see cref="BadgeType"/>.</param>
        static partial void OnDTO(this BadgeType entity, BadgeTypeEntity dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="BadgeType"/> converted from <see cref="BadgeTypeEntity"/>.</param>
        static partial void OnEntity(this BadgeTypeEntity dto, BadgeType entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="BadgeTypeEntity"/> to an instance of <see cref="BadgeType"/>.
        /// </summary>
        /// <param name="dto"><see cref="BadgeTypeEntity"/> to convert.</param>
        public static BadgeType ToEntity(this BadgeTypeEntity dto)
        {
            if (dto == null) return null;
    
            var entity = new BadgeType();
                 
            entity.Id = dto.Id;     
            entity.Type1 = dto.Type1;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="BadgeType"/> to an instance of <see cref="BadgeTypeEntity"/>.
        /// </summary>
        /// <param name="entity"><see cref="BadgeType"/> to convert.</param>
        public static BadgeTypeEntity ToDTO(this BadgeType entity)
        {
            if (entity == null) return null;
    
            var dto = new BadgeTypeEntity();
                 
            dto.Id = entity.Id;     
            dto.Type1 = entity.Type1;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="BadgeTypeEntity"/> to an instance of <see cref="BadgeType"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<BadgeType> ToEntities(this IEnumerable<BadgeTypeEntity> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="BadgeType"/> to an instance of <see cref="BadgeTypeEntity"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<BadgeTypeEntity> ToDTOs(this IEnumerable<BadgeType> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
