//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="BadgeTypeBadge"/> and <see cref="BadgeTypeBadgeDTO"/>.
    /// </summary>
    static public partial class BadgeTypeBadgeMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="BadgeTypeBadgeDTO"/> converted from <see cref="BadgeTypeBadge"/>.</param>
        static partial void OnDTO(this BadgeTypeBadge entity, BadgeTypeBadgeDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="BadgeTypeBadge"/> converted from <see cref="BadgeTypeBadgeDTO"/>.</param>
        static partial void OnEntity(this BadgeTypeBadgeDTO dto, BadgeTypeBadge entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="BadgeTypeBadgeDTO"/> to an instance of <see cref="BadgeTypeBadge"/>.
        /// </summary>
        /// <param name="dto"><see cref="BadgeTypeBadgeDTO"/> to convert.</param>
        public static BadgeTypeBadge ToEntity(this BadgeTypeBadgeDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new BadgeTypeBadge();
                 
            entity.BadgeTypeID = dto.BadgeTypeID;     
            entity.BadgeID = dto.BadgeID;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreatedDate = dto.CreatedDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="BadgeTypeBadge"/> to an instance of <see cref="BadgeTypeBadgeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="BadgeTypeBadge"/> to convert.</param>
        public static BadgeTypeBadgeDTO ToDTO(this BadgeTypeBadge entity)
        {
            if (entity == null) return null;
    
            var dto = new BadgeTypeBadgeDTO();
                 
            dto.BadgeTypeID = entity.BadgeTypeID;     
            dto.BadgeID = entity.BadgeID;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreatedDate = entity.CreatedDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="BadgeTypeBadgeDTO"/> to an instance of <see cref="BadgeTypeBadge"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<BadgeTypeBadge> ToEntities(this IEnumerable<BadgeTypeBadgeDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="BadgeTypeBadge"/> to an instance of <see cref="BadgeTypeBadgeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<BadgeTypeBadgeDTO> ToDTOs(this IEnumerable<BadgeTypeBadge> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
