//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="CampusStationHistory"/> and <see cref="CampusStationHistoryDTO"/>.
    /// </summary>
    static public partial class CampusStationHistoryMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="CampusStationHistoryDTO"/> converted from <see cref="CampusStationHistory"/>.</param>
        static partial void OnDTO(this CampusStationHistory entity, CampusStationHistoryDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="CampusStationHistory"/> converted from <see cref="CampusStationHistoryDTO"/>.</param>
        static partial void OnEntity(this CampusStationHistoryDTO dto, CampusStationHistory entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="CampusStationHistoryDTO"/> to an instance of <see cref="CampusStationHistory"/>.
        /// </summary>
        /// <param name="dto"><see cref="CampusStationHistoryDTO"/> to convert.</param>
        public static CampusStationHistory ToEntity(this CampusStationHistoryDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new CampusStationHistory();
                 
            entity.ID = dto.ID;     
            entity.CampusID = dto.CampusID;     
            entity.StationID = dto.StationID;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;     
            entity.AuditDate = dto.AuditDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="CampusStationHistory"/> to an instance of <see cref="CampusStationHistoryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="CampusStationHistory"/> to convert.</param>
        public static CampusStationHistoryDTO ToDTO(this CampusStationHistory entity)
        {
            if (entity == null) return null;
    
            var dto = new CampusStationHistoryDTO();
                 
            dto.ID = entity.ID;     
            dto.CampusID = entity.CampusID;     
            dto.StationID = entity.StationID;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;     
            dto.AuditDate = entity.AuditDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="CampusStationHistoryDTO"/> to an instance of <see cref="CampusStationHistory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<CampusStationHistory> ToEntities(this IEnumerable<CampusStationHistoryDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="CampusStationHistory"/> to an instance of <see cref="CampusStationHistoryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<CampusStationHistoryDTO> ToDTOs(this IEnumerable<CampusStationHistory> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
