//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="CampusHistory"/> and <see cref="CampusHistoryDTO"/>.
    /// </summary>
    static public partial class CampusHistoryMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="CampusHistoryDTO"/> converted from <see cref="CampusHistory"/>.</param>
        static partial void OnDTO(this CampusHistory entity, CampusHistoryDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="CampusHistory"/> converted from <see cref="CampusHistoryDTO"/>.</param>
        static partial void OnEntity(this CampusHistoryDTO dto, CampusHistory entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="CampusHistoryDTO"/> to an instance of <see cref="CampusHistory"/>.
        /// </summary>
        /// <param name="dto"><see cref="CampusHistoryDTO"/> to convert.</param>
        public static CampusHistory ToEntity(this CampusHistoryDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new CampusHistory();
                 
            entity.ID = dto.ID;     
            entity.CampusID = dto.CampusID;     
            entity.Code = dto.Code;     
            entity.Name = dto.Name;     
            entity.Address = dto.Address;     
            entity.Address2 = dto.Address2;     
            entity.City = dto.City;     
            entity.ZipCode = dto.ZipCode;     
            entity.IsActive = dto.IsActive;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;     
            entity.AuditDate = dto.AuditDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="CampusHistory"/> to an instance of <see cref="CampusHistoryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="CampusHistory"/> to convert.</param>
        public static CampusHistoryDTO ToDTO(this CampusHistory entity)
        {
            if (entity == null) return null;
    
            var dto = new CampusHistoryDTO();
                 
            dto.ID = entity.ID;     
            dto.CampusID = entity.CampusID;     
            dto.Code = entity.Code;     
            dto.Name = entity.Name;     
            dto.Address = entity.Address;     
            dto.Address2 = entity.Address2;     
            dto.City = entity.City;     
            dto.ZipCode = entity.ZipCode;     
            dto.IsActive = entity.IsActive;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;     
            dto.AuditDate = entity.AuditDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="CampusHistoryDTO"/> to an instance of <see cref="CampusHistory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<CampusHistory> ToEntities(this IEnumerable<CampusHistoryDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="CampusHistory"/> to an instance of <see cref="CampusHistoryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<CampusHistoryDTO> ToDTOs(this IEnumerable<CampusHistory> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
