//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="CampusLocationHistory"/> and <see cref="CampusLocationHistoryDTO"/>.
    /// </summary>
    static public partial class CampusLocationHistoryMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="CampusLocationHistoryDTO"/> converted from <see cref="CampusLocationHistory"/>.</param>
        static partial void OnDTO(this CampusLocationHistory entity, CampusLocationHistoryDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="CampusLocationHistory"/> converted from <see cref="CampusLocationHistoryDTO"/>.</param>
        static partial void OnEntity(this CampusLocationHistoryDTO dto, CampusLocationHistory entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="CampusLocationHistoryDTO"/> to an instance of <see cref="CampusLocationHistory"/>.
        /// </summary>
        /// <param name="dto"><see cref="CampusLocationHistoryDTO"/> to convert.</param>
        public static CampusLocationHistory ToEntity(this CampusLocationHistoryDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new CampusLocationHistory();
                 
            entity.ID = dto.ID;     
            entity.CampusID = dto.CampusID;     
            entity.LocationID = dto.LocationID;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;     
            entity.AuditDate = dto.AuditDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="CampusLocationHistory"/> to an instance of <see cref="CampusLocationHistoryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="CampusLocationHistory"/> to convert.</param>
        public static CampusLocationHistoryDTO ToDTO(this CampusLocationHistory entity)
        {
            if (entity == null) return null;
    
            var dto = new CampusLocationHistoryDTO();
                 
            dto.ID = entity.ID;     
            dto.CampusID = entity.CampusID;     
            dto.LocationID = entity.LocationID;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;     
            dto.AuditDate = entity.AuditDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="CampusLocationHistoryDTO"/> to an instance of <see cref="CampusLocationHistory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<CampusLocationHistory> ToEntities(this IEnumerable<CampusLocationHistoryDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="CampusLocationHistory"/> to an instance of <see cref="CampusLocationHistoryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<CampusLocationHistoryDTO> ToDTOs(this IEnumerable<CampusLocationHistory> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
