//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="Campu"/> and <see cref="CampuEntity"/>.
    /// </summary>
    static public partial class CampuMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="CampuEntity"/> converted from <see cref="Campu"/>.</param>
        static partial void OnDTO(this Campu entity, CampuEntity dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Campu"/> converted from <see cref="CampuEntity"/>.</param>
        static partial void OnEntity(this CampuEntity dto, Campu entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="CampuEntity"/> to an instance of <see cref="Campu"/>.
        /// </summary>
        /// <param name="dto"><see cref="CampuEntity"/> to convert.</param>
        public static Campu ToEntity(this CampuEntity dto)
        {
            if (dto == null) return null;
    
            var entity = new Campu();
                 
            entity.CampusID = dto.CampusID;     
            entity.Campus = dto.Campus;     
            entity.Active = dto.Active;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="Campu"/> to an instance of <see cref="CampuEntity"/>.
        /// </summary>
        /// <param name="entity"><see cref="Campu"/> to convert.</param>
        public static CampuEntity ToDTO(this Campu entity)
        {
            if (entity == null) return null;
    
            var dto = new CampuEntity();
                 
            dto.CampusID = entity.CampusID;     
            dto.Campus = entity.Campus;     
            dto.Active = entity.Active;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="CampuEntity"/> to an instance of <see cref="Campu"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Campu> ToEntities(this IEnumerable<CampuEntity> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="Campu"/> to an instance of <see cref="CampuEntity"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<CampuEntity> ToDTOs(this IEnumerable<Campu> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
