//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="CompanyHistory"/> and <see cref="CompanyHistoryDTO"/>.
    /// </summary>
    static public partial class CompanyHistoryMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="CompanyHistoryDTO"/> converted from <see cref="CompanyHistory"/>.</param>
        static partial void OnDTO(this CompanyHistory entity, CompanyHistoryDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="CompanyHistory"/> converted from <see cref="CompanyHistoryDTO"/>.</param>
        static partial void OnEntity(this CompanyHistoryDTO dto, CompanyHistory entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="CompanyHistoryDTO"/> to an instance of <see cref="CompanyHistory"/>.
        /// </summary>
        /// <param name="dto"><see cref="CompanyHistoryDTO"/> to convert.</param>
        public static CompanyHistory ToEntity(this CompanyHistoryDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new CompanyHistory();
                 
            entity.ID = dto.ID;     
            entity.CompanyID = dto.CompanyID;     
            entity.Name = dto.Name;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="CompanyHistory"/> to an instance of <see cref="CompanyHistoryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="CompanyHistory"/> to convert.</param>
        public static CompanyHistoryDTO ToDTO(this CompanyHistory entity)
        {
            if (entity == null) return null;
    
            var dto = new CompanyHistoryDTO();
                 
            dto.ID = entity.ID;     
            dto.CompanyID = entity.CompanyID;     
            dto.Name = entity.Name;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="CompanyHistoryDTO"/> to an instance of <see cref="CompanyHistory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<CompanyHistory> ToEntities(this IEnumerable<CompanyHistoryDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="CompanyHistory"/> to an instance of <see cref="CompanyHistoryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<CompanyHistoryDTO> ToDTOs(this IEnumerable<CompanyHistory> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
