//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="Company"/> and <see cref="CompanyDTO"/>.
    /// </summary>
    static public partial class CompanyMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="CompanyDTO"/> converted from <see cref="Company"/>.</param>
        static partial void OnDTO(this Company entity, CompanyDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Company"/> converted from <see cref="CompanyDTO"/>.</param>
        static partial void OnEntity(this CompanyDTO dto, Company entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="CompanyDTO"/> to an instance of <see cref="Company"/>.
        /// </summary>
        /// <param name="dto"><see cref="CompanyDTO"/> to convert.</param>
        public static Company ToEntity(this CompanyDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new Company();
                 
            entity.ID = dto.ID;     
            entity.Name = dto.Name;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreatedDate = dto.CreatedDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="Company"/> to an instance of <see cref="CompanyDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Company"/> to convert.</param>
        public static CompanyDTO ToDTO(this Company entity)
        {
            if (entity == null) return null;
    
            var dto = new CompanyDTO();
                 
            dto.ID = entity.ID;     
            dto.Name = entity.Name;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreatedDate = entity.CreatedDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="CompanyDTO"/> to an instance of <see cref="Company"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Company> ToEntities(this IEnumerable<CompanyDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="Company"/> to an instance of <see cref="CompanyDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<CompanyDTO> ToDTOs(this IEnumerable<Company> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
