//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="Contact"/> and <see cref="ContactDTO"/>.
    /// </summary>
    static public partial class ContactMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="ContactDTO"/> converted from <see cref="Contact"/>.</param>
        static partial void OnDTO(this Contact entity, ContactDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Contact"/> converted from <see cref="ContactDTO"/>.</param>
        static partial void OnEntity(this ContactDTO dto, Contact entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="ContactDTO"/> to an instance of <see cref="Contact"/>.
        /// </summary>
        /// <param name="dto"><see cref="ContactDTO"/> to convert.</param>
        public static Contact ToEntity(this ContactDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new Contact();
                 
            entity.ID = dto.ID;     
            entity.ContactUserID = dto.ContactUserID;     
            entity.Phone = dto.Phone;     
            entity.Mobile = dto.Mobile;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreatedDate = dto.CreatedDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="Contact"/> to an instance of <see cref="ContactDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Contact"/> to convert.</param>
        public static ContactDTO ToDTO(this Contact entity)
        {
            if (entity == null) return null;
    
            var dto = new ContactDTO();
                 
            dto.ID = entity.ID;     
            dto.ContactUserID = entity.ContactUserID;     
            dto.Phone = entity.Phone;     
            dto.Mobile = entity.Mobile;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreatedDate = entity.CreatedDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="ContactDTO"/> to an instance of <see cref="Contact"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Contact> ToEntities(this IEnumerable<ContactDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="Contact"/> to an instance of <see cref="ContactDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<ContactDTO> ToDTOs(this IEnumerable<Contact> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
