//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="EmployeeRole"/> and <see cref="EmployeeRoleEntity"/>.
    /// </summary>
    static public partial class EmployeeRoleMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="EmployeeRoleEntity"/> converted from <see cref="EmployeeRole"/>.</param>
        static partial void OnDTO(this EmployeeRole entity, EmployeeRoleEntity dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="EmployeeRole"/> converted from <see cref="EmployeeRoleEntity"/>.</param>
        static partial void OnEntity(this EmployeeRoleEntity dto, EmployeeRole entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="EmployeeRoleEntity"/> to an instance of <see cref="EmployeeRole"/>.
        /// </summary>
        /// <param name="dto"><see cref="EmployeeRoleEntity"/> to convert.</param>
        public static EmployeeRole ToEntity(this EmployeeRoleEntity dto)
        {
            if (dto == null) return null;
    
            var entity = new EmployeeRole();
                 
            entity.EmployeeId = dto.EmployeeId;     
            entity.RoleId = dto.RoleId;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="EmployeeRole"/> to an instance of <see cref="EmployeeRoleEntity"/>.
        /// </summary>
        /// <param name="entity"><see cref="EmployeeRole"/> to convert.</param>
        public static EmployeeRoleEntity ToDTO(this EmployeeRole entity)
        {
            if (entity == null) return null;
    
            var dto = new EmployeeRoleEntity();
                 
            dto.EmployeeId = entity.EmployeeId;     
            dto.RoleId = entity.RoleId;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="EmployeeRoleEntity"/> to an instance of <see cref="EmployeeRole"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<EmployeeRole> ToEntities(this IEnumerable<EmployeeRoleEntity> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="EmployeeRole"/> to an instance of <see cref="EmployeeRoleEntity"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<EmployeeRoleEntity> ToDTOs(this IEnumerable<EmployeeRole> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
