//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="Location"/> and <see cref="LocationDTO"/>.
    /// </summary>
    static public partial class LocationMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="LocationDTO"/> converted from <see cref="Location"/>.</param>
        static partial void OnDTO(this Location entity, LocationDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Location"/> converted from <see cref="LocationDTO"/>.</param>
        static partial void OnEntity(this LocationDTO dto, Location entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="LocationDTO"/> to an instance of <see cref="Location"/>.
        /// </summary>
        /// <param name="dto"><see cref="LocationDTO"/> to convert.</param>
        public static Location ToEntity(this LocationDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new Location();
                 
            entity.ID = dto.ID;     
            entity.Name = dto.Name;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreatedDate = dto.CreatedDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="Location"/> to an instance of <see cref="LocationDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Location"/> to convert.</param>
        public static LocationDTO ToDTO(this Location entity)
        {
            if (entity == null) return null;
    
            var dto = new LocationDTO();
                 
            dto.ID = entity.ID;     
            dto.Name = entity.Name;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreatedDate = entity.CreatedDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="LocationDTO"/> to an instance of <see cref="Location"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Location> ToEntities(this IEnumerable<LocationDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="Location"/> to an instance of <see cref="LocationDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<LocationDTO> ToDTOs(this IEnumerable<Location> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
