//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="LocationHistory"/> and <see cref="LocationHistoryDTO"/>.
    /// </summary>
    static public partial class LocationHistoryMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="LocationHistoryDTO"/> converted from <see cref="LocationHistory"/>.</param>
        static partial void OnDTO(this LocationHistory entity, LocationHistoryDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="LocationHistory"/> converted from <see cref="LocationHistoryDTO"/>.</param>
        static partial void OnEntity(this LocationHistoryDTO dto, LocationHistory entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="LocationHistoryDTO"/> to an instance of <see cref="LocationHistory"/>.
        /// </summary>
        /// <param name="dto"><see cref="LocationHistoryDTO"/> to convert.</param>
        public static LocationHistory ToEntity(this LocationHistoryDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new LocationHistory();
                 
            entity.ID = dto.ID;     
            entity.LocationID = dto.LocationID;     
            entity.Name = dto.Name;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;     
            entity.AuditDate = dto.AuditDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="LocationHistory"/> to an instance of <see cref="LocationHistoryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="LocationHistory"/> to convert.</param>
        public static LocationHistoryDTO ToDTO(this LocationHistory entity)
        {
            if (entity == null) return null;
    
            var dto = new LocationHistoryDTO();
                 
            dto.ID = entity.ID;     
            dto.LocationID = entity.LocationID;     
            dto.Name = entity.Name;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;     
            dto.AuditDate = entity.AuditDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="LocationHistoryDTO"/> to an instance of <see cref="LocationHistory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<LocationHistory> ToEntities(this IEnumerable<LocationHistoryDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="LocationHistory"/> to an instance of <see cref="LocationHistoryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<LocationHistoryDTO> ToDTOs(this IEnumerable<LocationHistory> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
