//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="LogCounter"/> and <see cref="LogCounterEntity"/>.
    /// </summary>
    static public partial class LogCounterMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="LogCounterEntity"/> converted from <see cref="LogCounter"/>.</param>
        static partial void OnDTO(this LogCounter entity, LogCounterEntity dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="LogCounter"/> converted from <see cref="LogCounterEntity"/>.</param>
        static partial void OnEntity(this LogCounterEntity dto, LogCounter entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="LogCounterEntity"/> to an instance of <see cref="LogCounter"/>.
        /// </summary>
        /// <param name="dto"><see cref="LogCounterEntity"/> to convert.</param>
        public static LogCounter ToEntity(this LogCounterEntity dto)
        {
            if (dto == null) return null;
    
            var entity = new LogCounter();
                 
            entity.FY = dto.FY;     
            entity.LogNoCounter = dto.LogNoCounter;     
            entity.LogCounterID = dto.LogCounterID;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="LogCounter"/> to an instance of <see cref="LogCounterEntity"/>.
        /// </summary>
        /// <param name="entity"><see cref="LogCounter"/> to convert.</param>
        public static LogCounterEntity ToDTO(this LogCounter entity)
        {
            if (entity == null) return null;
    
            var dto = new LogCounterEntity();
                 
            dto.FY = entity.FY;     
            dto.LogNoCounter = entity.LogNoCounter;     
            dto.LogCounterID = entity.LogCounterID;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="LogCounterEntity"/> to an instance of <see cref="LogCounter"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<LogCounter> ToEntities(this IEnumerable<LogCounterEntity> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="LogCounter"/> to an instance of <see cref="LogCounterEntity"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<LogCounterEntity> ToDTOs(this IEnumerable<LogCounter> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
