//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="LogVisitor"/> and <see cref="LogVisitorDTO"/>.
    /// </summary>
    static public partial class LogVisitorMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="LogVisitorDTO"/> converted from <see cref="LogVisitor"/>.</param>
        static partial void OnDTO(this LogVisitor entity, LogVisitorDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="LogVisitor"/> converted from <see cref="LogVisitorDTO"/>.</param>
        static partial void OnEntity(this LogVisitorDTO dto, LogVisitor entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="LogVisitorDTO"/> to an instance of <see cref="LogVisitor"/>.
        /// </summary>
        /// <param name="dto"><see cref="LogVisitorDTO"/> to convert.</param>
        public static LogVisitor ToEntity(this LogVisitorDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new LogVisitor();
                 
            entity.LogID = dto.LogID;     
            entity.VisitorID = dto.VisitorID;     
            entity.ContactID = dto.ContactID;     
            entity.LocationID = dto.LocationID;     
            entity.CompanyID = dto.CompanyID;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreatedDate = dto.CreatedDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="LogVisitor"/> to an instance of <see cref="LogVisitorDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="LogVisitor"/> to convert.</param>
        public static LogVisitorDTO ToDTO(this LogVisitor entity)
        {
            if (entity == null) return null;
    
            var dto = new LogVisitorDTO();
                 
            dto.LogID = entity.LogID;     
            dto.VisitorID = entity.VisitorID;     
            dto.ContactID = entity.ContactID;     
            dto.LocationID = entity.LocationID;     
            dto.CompanyID = entity.CompanyID;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreatedDate = entity.CreatedDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="LogVisitorDTO"/> to an instance of <see cref="LogVisitor"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<LogVisitor> ToEntities(this IEnumerable<LogVisitorDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="LogVisitor"/> to an instance of <see cref="LogVisitorDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<LogVisitorDTO> ToDTOs(this IEnumerable<LogVisitor> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
