//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="LogVisit"/> and <see cref="LogVisitDTO"/>.
    /// </summary>
    static public partial class LogVisitMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="LogVisitDTO"/> converted from <see cref="LogVisit"/>.</param>
        static partial void OnDTO(this LogVisit entity, LogVisitDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="LogVisit"/> converted from <see cref="LogVisitDTO"/>.</param>
        static partial void OnEntity(this LogVisitDTO dto, LogVisit entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="LogVisitDTO"/> to an instance of <see cref="LogVisit"/>.
        /// </summary>
        /// <param name="dto"><see cref="LogVisitDTO"/> to convert.</param>
        public static LogVisit ToEntity(this LogVisitDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new LogVisit();
                 
            entity.LogID = dto.LogID;     
            entity.VisitID = dto.VisitID;     
            entity.VisitorID = dto.VisitorID;     
            entity.BadgeID = dto.BadgeID;     
            entity.AssetID = dto.AssetID;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreatedDate = dto.CreatedDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="LogVisit"/> to an instance of <see cref="LogVisitDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="LogVisit"/> to convert.</param>
        public static LogVisitDTO ToDTO(this LogVisit entity)
        {
            if (entity == null) return null;
    
            var dto = new LogVisitDTO();
                 
            dto.LogID = entity.LogID;     
            dto.VisitID = entity.VisitID;     
            dto.VisitorID = entity.VisitorID;     
            dto.BadgeID = entity.BadgeID;     
            dto.AssetID = entity.AssetID;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreatedDate = entity.CreatedDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="LogVisitDTO"/> to an instance of <see cref="LogVisit"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<LogVisit> ToEntities(this IEnumerable<LogVisitDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="LogVisit"/> to an instance of <see cref="LogVisitDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<LogVisitDTO> ToDTOs(this IEnumerable<LogVisit> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
