//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="SecuredArea"/> and <see cref="SecuredAreaEntity"/>.
    /// </summary>
    static public partial class SecuredAreaMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="SecuredAreaEntity"/> converted from <see cref="SecuredArea"/>.</param>
        static partial void OnDTO(this SecuredArea entity, SecuredAreaEntity dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="SecuredArea"/> converted from <see cref="SecuredAreaEntity"/>.</param>
        static partial void OnEntity(this SecuredAreaEntity dto, SecuredArea entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="SecuredAreaEntity"/> to an instance of <see cref="SecuredArea"/>.
        /// </summary>
        /// <param name="dto"><see cref="SecuredAreaEntity"/> to convert.</param>
        public static SecuredArea ToEntity(this SecuredAreaEntity dto)
        {
            if (dto == null) return null;
    
            var entity = new SecuredArea();
                 
            entity.Id = dto.Id;     
            entity.SecuredArea1 = dto.SecuredArea1;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="SecuredArea"/> to an instance of <see cref="SecuredAreaEntity"/>.
        /// </summary>
        /// <param name="entity"><see cref="SecuredArea"/> to convert.</param>
        public static SecuredAreaEntity ToDTO(this SecuredArea entity)
        {
            if (entity == null) return null;
    
            var dto = new SecuredAreaEntity();
                 
            dto.Id = entity.Id;     
            dto.SecuredArea1 = entity.SecuredArea1;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="SecuredAreaEntity"/> to an instance of <see cref="SecuredArea"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<SecuredArea> ToEntities(this IEnumerable<SecuredAreaEntity> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="SecuredArea"/> to an instance of <see cref="SecuredAreaEntity"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<SecuredAreaEntity> ToDTOs(this IEnumerable<SecuredArea> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
