//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="StationHistory"/> and <see cref="StationHistoryDTO"/>.
    /// </summary>
    static public partial class StationHistoryMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="StationHistoryDTO"/> converted from <see cref="StationHistory"/>.</param>
        static partial void OnDTO(this StationHistory entity, StationHistoryDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="StationHistory"/> converted from <see cref="StationHistoryDTO"/>.</param>
        static partial void OnEntity(this StationHistoryDTO dto, StationHistory entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="StationHistoryDTO"/> to an instance of <see cref="StationHistory"/>.
        /// </summary>
        /// <param name="dto"><see cref="StationHistoryDTO"/> to convert.</param>
        public static StationHistory ToEntity(this StationHistoryDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new StationHistory();
                 
            entity.ID = dto.ID;     
            entity.StationID = dto.StationID;     
            entity.Code = dto.Code;     
            entity.Name = dto.Name;     
            entity.IsActive = dto.IsActive;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;     
            entity.AuditDate = dto.AuditDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="StationHistory"/> to an instance of <see cref="StationHistoryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="StationHistory"/> to convert.</param>
        public static StationHistoryDTO ToDTO(this StationHistory entity)
        {
            if (entity == null) return null;
    
            var dto = new StationHistoryDTO();
                 
            dto.ID = entity.ID;     
            dto.StationID = entity.StationID;     
            dto.Code = entity.Code;     
            dto.Name = entity.Name;     
            dto.IsActive = entity.IsActive;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;     
            dto.AuditDate = entity.AuditDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="StationHistoryDTO"/> to an instance of <see cref="StationHistory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<StationHistory> ToEntities(this IEnumerable<StationHistoryDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="StationHistory"/> to an instance of <see cref="StationHistoryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<StationHistoryDTO> ToDTOs(this IEnumerable<StationHistory> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
