//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="sysdiagram"/> and <see cref="sysdiagramEntity"/>.
    /// </summary>
    static public partial class sysdiagramMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="sysdiagramEntity"/> converted from <see cref="sysdiagram"/>.</param>
        static partial void OnDTO(this sysdiagram entity, sysdiagramEntity dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="sysdiagram"/> converted from <see cref="sysdiagramEntity"/>.</param>
        static partial void OnEntity(this sysdiagramEntity dto, sysdiagram entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="sysdiagramEntity"/> to an instance of <see cref="sysdiagram"/>.
        /// </summary>
        /// <param name="dto"><see cref="sysdiagramEntity"/> to convert.</param>
        public static sysdiagram ToEntity(this sysdiagramEntity dto)
        {
            if (dto == null) return null;
    
            var entity = new sysdiagram();
                 
            entity.name = dto.name;     
            entity.principal_id = dto.principal_id;     
            entity.diagram_id = dto.diagram_id;     
            entity.version = dto.version;     
            entity.definition = dto.definition;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="sysdiagram"/> to an instance of <see cref="sysdiagramEntity"/>.
        /// </summary>
        /// <param name="entity"><see cref="sysdiagram"/> to convert.</param>
        public static sysdiagramEntity ToDTO(this sysdiagram entity)
        {
            if (entity == null) return null;
    
            var dto = new sysdiagramEntity();
                 
            dto.name = entity.name;     
            dto.principal_id = entity.principal_id;     
            dto.diagram_id = entity.diagram_id;     
            dto.version = entity.version;     
            dto.definition = entity.definition;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="sysdiagramEntity"/> to an instance of <see cref="sysdiagram"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<sysdiagram> ToEntities(this IEnumerable<sysdiagramEntity> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="sysdiagram"/> to an instance of <see cref="sysdiagramEntity"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<sysdiagramEntity> ToDTOs(this IEnumerable<sysdiagram> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
