//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="TenantDepartment"/> and <see cref="TenantDepartmentEntity"/>.
    /// </summary>
    static public partial class TenantDepartmentMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="TenantDepartmentEntity"/> converted from <see cref="TenantDepartment"/>.</param>
        static partial void OnDTO(this TenantDepartment entity, TenantDepartmentEntity dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="TenantDepartment"/> converted from <see cref="TenantDepartmentEntity"/>.</param>
        static partial void OnEntity(this TenantDepartmentEntity dto, TenantDepartment entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="TenantDepartmentEntity"/> to an instance of <see cref="TenantDepartment"/>.
        /// </summary>
        /// <param name="dto"><see cref="TenantDepartmentEntity"/> to convert.</param>
        public static TenantDepartment ToEntity(this TenantDepartmentEntity dto)
        {
            if (dto == null) return null;
    
            var entity = new TenantDepartment();
                 
            entity.Id = dto.Id;     
            entity.TenantDepartment1 = dto.TenantDepartment1;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="TenantDepartment"/> to an instance of <see cref="TenantDepartmentEntity"/>.
        /// </summary>
        /// <param name="entity"><see cref="TenantDepartment"/> to convert.</param>
        public static TenantDepartmentEntity ToDTO(this TenantDepartment entity)
        {
            if (entity == null) return null;
    
            var dto = new TenantDepartmentEntity();
                 
            dto.Id = entity.Id;     
            dto.TenantDepartment1 = entity.TenantDepartment1;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="TenantDepartmentEntity"/> to an instance of <see cref="TenantDepartment"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<TenantDepartment> ToEntities(this IEnumerable<TenantDepartmentEntity> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="TenantDepartment"/> to an instance of <see cref="TenantDepartmentEntity"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<TenantDepartmentEntity> ToDTOs(this IEnumerable<TenantDepartment> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
