//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="Visitor"/> and <see cref="VisitorDTO"/>.
    /// </summary>
    static public partial class VisitorMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="VisitorDTO"/> converted from <see cref="Visitor"/>.</param>
        static partial void OnDTO(this Visitor entity, VisitorDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Visitor"/> converted from <see cref="VisitorDTO"/>.</param>
        static partial void OnEntity(this VisitorDTO dto, Visitor entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="VisitorDTO"/> to an instance of <see cref="Visitor"/>.
        /// </summary>
        /// <param name="dto"><see cref="VisitorDTO"/> to convert.</param>
        public static Visitor ToEntity(this VisitorDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new Visitor();
                 
            entity.ID = dto.ID;     
            entity.FirstName = dto.FirstName;     
            entity.LastName = dto.LastName;     
            entity.PersonIDCardNumber = dto.PersonIDCardNumber;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreatedDate = dto.CreatedDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="Visitor"/> to an instance of <see cref="VisitorDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Visitor"/> to convert.</param>
        public static VisitorDTO ToDTO(this Visitor entity)
        {
            if (entity == null) return null;
    
            var dto = new VisitorDTO();
                 
            dto.ID = entity.ID;     
            dto.FirstName = entity.FirstName;     
            dto.LastName = entity.LastName;     
            dto.PersonIDCardNumber = entity.PersonIDCardNumber;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreatedDate = entity.CreatedDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitorDTO"/> to an instance of <see cref="Visitor"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Visitor> ToEntities(this IEnumerable<VisitorDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="Visitor"/> to an instance of <see cref="VisitorDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<VisitorDTO> ToDTOs(this IEnumerable<Visitor> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
