//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="VisitorBadge"/> and <see cref="VisitorBadgeDTO"/>.
    /// </summary>
    static public partial class VisitorBadgeMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="VisitorBadgeDTO"/> converted from <see cref="VisitorBadge"/>.</param>
        static partial void OnDTO(this VisitorBadge entity, VisitorBadgeDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="VisitorBadge"/> converted from <see cref="VisitorBadgeDTO"/>.</param>
        static partial void OnEntity(this VisitorBadgeDTO dto, VisitorBadge entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="VisitorBadgeDTO"/> to an instance of <see cref="VisitorBadge"/>.
        /// </summary>
        /// <param name="dto"><see cref="VisitorBadgeDTO"/> to convert.</param>
        public static VisitorBadge ToEntity(this VisitorBadgeDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new VisitorBadge();
                 
            entity.VisitorID = dto.VisitorID;     
            entity.BadgeID = dto.BadgeID;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreatedDate = dto.CreatedDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="VisitorBadge"/> to an instance of <see cref="VisitorBadgeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="VisitorBadge"/> to convert.</param>
        public static VisitorBadgeDTO ToDTO(this VisitorBadge entity)
        {
            if (entity == null) return null;
    
            var dto = new VisitorBadgeDTO();
                 
            dto.VisitorID = entity.VisitorID;     
            dto.BadgeID = entity.BadgeID;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreatedDate = entity.CreatedDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitorBadgeDTO"/> to an instance of <see cref="VisitorBadge"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<VisitorBadge> ToEntities(this IEnumerable<VisitorBadgeDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitorBadge"/> to an instance of <see cref="VisitorBadgeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<VisitorBadgeDTO> ToDTOs(this IEnumerable<VisitorBadge> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
