//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="VisitorCompany"/> and <see cref="VisitorCompanyDTO"/>.
    /// </summary>
    static public partial class VisitorCompanyMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="VisitorCompanyDTO"/> converted from <see cref="VisitorCompany"/>.</param>
        static partial void OnDTO(this VisitorCompany entity, VisitorCompanyDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="VisitorCompany"/> converted from <see cref="VisitorCompanyDTO"/>.</param>
        static partial void OnEntity(this VisitorCompanyDTO dto, VisitorCompany entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="VisitorCompanyDTO"/> to an instance of <see cref="VisitorCompany"/>.
        /// </summary>
        /// <param name="dto"><see cref="VisitorCompanyDTO"/> to convert.</param>
        public static VisitorCompany ToEntity(this VisitorCompanyDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new VisitorCompany();
                 
            entity.VisitorID = dto.VisitorID;     
            entity.CompanyID = dto.CompanyID;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreatedDate = dto.CreatedDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="VisitorCompany"/> to an instance of <see cref="VisitorCompanyDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="VisitorCompany"/> to convert.</param>
        public static VisitorCompanyDTO ToDTO(this VisitorCompany entity)
        {
            if (entity == null) return null;
    
            var dto = new VisitorCompanyDTO();
                 
            dto.VisitorID = entity.VisitorID;     
            dto.CompanyID = entity.CompanyID;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreatedDate = entity.CreatedDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitorCompanyDTO"/> to an instance of <see cref="VisitorCompany"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<VisitorCompany> ToEntities(this IEnumerable<VisitorCompanyDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitorCompany"/> to an instance of <see cref="VisitorCompanyDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<VisitorCompanyDTO> ToDTOs(this IEnumerable<VisitorCompany> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
