//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="VisitorDetail"/> and <see cref="VisitorDetailEntity"/>.
    /// </summary>
    static public partial class VisitorDetailMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="VisitorDetailEntity"/> converted from <see cref="VisitorDetail"/>.</param>
        static partial void OnDTO(this VisitorDetail entity, VisitorDetailEntity dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="VisitorDetail"/> converted from <see cref="VisitorDetailEntity"/>.</param>
        static partial void OnEntity(this VisitorDetailEntity dto, VisitorDetail entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="VisitorDetailEntity"/> to an instance of <see cref="VisitorDetail"/>.
        /// </summary>
        /// <param name="dto"><see cref="VisitorDetailEntity"/> to convert.</param>
        public static VisitorDetail ToEntity(this VisitorDetailEntity dto)
        {
            if (dto == null) return null;
    
            var entity = new VisitorDetail();
                 
            entity.VisitID = dto.VisitID;     
            entity.VisitorNo = dto.VisitorNo;     
            entity.VisitDate = dto.VisitDate;     
            entity.CheckInTime = dto.CheckInTime;     
            entity.CheckOutTime = dto.CheckOutTime;     
            entity.EquipmentInfo = dto.EquipmentInfo;     
            entity.BadgeNo = dto.BadgeNo;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="VisitorDetail"/> to an instance of <see cref="VisitorDetailEntity"/>.
        /// </summary>
        /// <param name="entity"><see cref="VisitorDetail"/> to convert.</param>
        public static VisitorDetailEntity ToDTO(this VisitorDetail entity)
        {
            if (entity == null) return null;
    
            var dto = new VisitorDetailEntity();
                 
            dto.VisitID = entity.VisitID;     
            dto.VisitorNo = entity.VisitorNo;     
            dto.VisitDate = entity.VisitDate;     
            dto.CheckInTime = entity.CheckInTime;     
            dto.CheckOutTime = entity.CheckOutTime;     
            dto.EquipmentInfo = entity.EquipmentInfo;     
            dto.BadgeNo = entity.BadgeNo;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitorDetailEntity"/> to an instance of <see cref="VisitorDetail"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<VisitorDetail> ToEntities(this IEnumerable<VisitorDetailEntity> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitorDetail"/> to an instance of <see cref="VisitorDetailEntity"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<VisitorDetailEntity> ToDTOs(this IEnumerable<VisitorDetail> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
