//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Johnny Vu
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="VisitorFile"/> and <see cref="VisitorFileEntity"/>.
    /// </summary>
    static public partial class VisitorFileMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="VisitorFileEntity"/> converted from <see cref="VisitorFile"/>.</param>
        static partial void OnDTO(this VisitorFile entity, VisitorFileEntity dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="VisitorFile"/> converted from <see cref="VisitorFileEntity"/>.</param>
        static partial void OnEntity(this VisitorFileEntity dto, VisitorFile entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="VisitorFileEntity"/> to an instance of <see cref="VisitorFile"/>.
        /// </summary>
        /// <param name="dto"><see cref="VisitorFileEntity"/> to convert.</param>
        public static VisitorFile ToEntity(this VisitorFileEntity dto)
        {
            if (dto == null) return null;
    
            var entity = new VisitorFile();
                 
            entity.ID = dto.ID;     
            entity.VisitID = dto.VisitID;     
            entity.FileName = dto.FileName;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="VisitorFile"/> to an instance of <see cref="VisitorFileEntity"/>.
        /// </summary>
        /// <param name="entity"><see cref="VisitorFile"/> to convert.</param>
        public static VisitorFileEntity ToDTO(this VisitorFile entity)
        {
            if (entity == null) return null;
    
            var dto = new VisitorFileEntity();
                 
            dto.ID = entity.ID;     
            dto.VisitID = entity.VisitID;     
            dto.FileName = entity.FileName;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitorFileEntity"/> to an instance of <see cref="VisitorFile"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<VisitorFile> ToEntities(this IEnumerable<VisitorFileEntity> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitorFile"/> to an instance of <see cref="VisitorFileEntity"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<VisitorFileEntity> ToDTOs(this IEnumerable<VisitorFile> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
