//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="VisitVisitorHistory"/> and <see cref="VisitVisitorHistoryDTO"/>.
    /// </summary>
    static public partial class VisitVisitorHistoryMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="VisitVisitorHistoryDTO"/> converted from <see cref="VisitVisitorHistory"/>.</param>
        static partial void OnDTO(this VisitVisitorHistory entity, VisitVisitorHistoryDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="VisitVisitorHistory"/> converted from <see cref="VisitVisitorHistoryDTO"/>.</param>
        static partial void OnEntity(this VisitVisitorHistoryDTO dto, VisitVisitorHistory entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="VisitVisitorHistoryDTO"/> to an instance of <see cref="VisitVisitorHistory"/>.
        /// </summary>
        /// <param name="dto"><see cref="VisitVisitorHistoryDTO"/> to convert.</param>
        public static VisitVisitorHistory ToEntity(this VisitVisitorHistoryDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new VisitVisitorHistory();
                 
            entity.ID = dto.ID;     
            entity.VisitID = dto.VisitID;     
            entity.VisitorID = dto.VisitorID;     
            entity.ContactUserID = dto.ContactUserID;     
            entity.LocationID = dto.LocationID;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;     
            entity.AuditDate = dto.AuditDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="VisitVisitorHistory"/> to an instance of <see cref="VisitVisitorHistoryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="VisitVisitorHistory"/> to convert.</param>
        public static VisitVisitorHistoryDTO ToDTO(this VisitVisitorHistory entity)
        {
            if (entity == null) return null;
    
            var dto = new VisitVisitorHistoryDTO();
                 
            dto.ID = entity.ID;     
            dto.VisitID = entity.VisitID;     
            dto.VisitorID = entity.VisitorID;     
            dto.ContactUserID = entity.ContactUserID;     
            dto.LocationID = entity.LocationID;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;     
            dto.AuditDate = entity.AuditDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitVisitorHistoryDTO"/> to an instance of <see cref="VisitVisitorHistory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<VisitVisitorHistory> ToEntities(this IEnumerable<VisitVisitorHistoryDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitVisitorHistory"/> to an instance of <see cref="VisitVisitorHistoryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<VisitVisitorHistoryDTO> ToDTOs(this IEnumerable<VisitVisitorHistory> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
