//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// 
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Services.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using VL.Business.Entities;
    using VL.Data.Model;
    
    /// <summary>
    /// DTO Mapper for <see cref="VisitorVisit"/> and <see cref="VisitorVisitDTO"/>.
    /// </summary>
    static public partial class VisitorVisitMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="VisitorVisitDTO"/> converted from <see cref="VisitorVisit"/>.</param>
        static partial void OnDTO(this VisitorVisit entity, VisitorVisitDTO dto);
       
        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="VisitorVisit"/> converted from <see cref="VisitorVisitDTO"/>.</param>
        static partial void OnEntity(this VisitorVisitDTO dto, VisitorVisit entity);
    
    
        /// <summary>
        /// Converts this instance of <see cref="VisitorVisitDTO"/> to an instance of <see cref="VisitorVisit"/>.
        /// </summary>
        /// <param name="dto"><see cref="VisitorVisitDTO"/> to convert.</param>
        public static VisitorVisit ToEntity(this VisitorVisitDTO dto)
        {
            if (dto == null) return null;
    
            var entity = new VisitorVisit();
                 
            entity.VisitorID = dto.VisitorID;     
            entity.VisitID = dto.VisitID;     
            entity.AssetID = dto.AssetID;     
            entity.Comment = dto.Comment;     
            entity.CreatedByUserID = dto.CreatedByUserID;     
            entity.CreatedDate = dto.CreatedDate;     
            entity.ModifiedByUserID = dto.ModifiedByUserID;     
            entity.ModifiedDate = dto.ModifiedDate;        
            dto.OnEntity(entity);
    
            return entity;
        }
    
        /// <summary>
        /// Converts this instance of <see cref="VisitorVisit"/> to an instance of <see cref="VisitorVisitDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="VisitorVisit"/> to convert.</param>
        public static VisitorVisitDTO ToDTO(this VisitorVisit entity)
        {
            if (entity == null) return null;
    
            var dto = new VisitorVisitDTO();
                 
            dto.VisitorID = entity.VisitorID;     
            dto.VisitID = entity.VisitID;     
            dto.AssetID = entity.AssetID;     
            dto.Comment = entity.Comment;     
            dto.CreatedByUserID = entity.CreatedByUserID;     
            dto.CreatedDate = entity.CreatedDate;     
            dto.ModifiedByUserID = entity.ModifiedByUserID;     
            dto.ModifiedDate = entity.ModifiedDate;
            entity.OnDTO(dto);
    
            return dto;
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitorVisitDTO"/> to an instance of <see cref="VisitorVisit"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<VisitorVisit> ToEntities(this IEnumerable<VisitorVisitDTO> dtos)
        {
            if (dtos == null) return null;
    
            return dtos.Select(e => e.ToEntity()).ToList();
        }
    
        /// <summary>
        /// Converts each instance of <see cref="VisitorVisit"/> to an instance of <see cref="VisitorVisitDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<VisitorVisitDTO> ToDTOs(this IEnumerable<VisitorVisit> entities)
        {
            if (entities == null) return null;
    
            return entities.Select(e => e.ToDTO()).ToList();
        }
    
    }
}
