//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from the Entity.tt T4 template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [DataContract(IsReference=true)]
    public partial class AccessAreaEntity
    {
        
        public AccessAreaEntity()
        {
            this.VisitorLogAccessIDs = new List<VisitorLogAccessIDEntity>();
        }
    
    
        [DataMember()]
        public short AccessID { get; set; }
    
        [DataMember()]
        public byte CampusID { get; set; }
    
        [DataMember()]
        public string Access { get; set; }
    
        [DataMember()]
        public bool Active { get; set; }
    
        #region [Navigation Properties]
    
        [DataMember()]
        public CampuEntity Campu { get; set; }
    
        [DataMember()]
        public List<VisitorLogAccessIDEntity> VisitorLogAccessIDs { get; set; }
                
        #endregion [Navigation Properties]
    
    }
    
}
