//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from the Entity.tt T4 template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [DataContract(IsReference=true)]
    public partial class EmpRefEntity
    {
    
        [DataMember()]
        public int EmpID { get; set; }
    
        [DataMember()]
        public string FullName { get; set; }
    
        [DataMember()]
        public string FirstName { get; set; }
    
        [DataMember()]
        public string LastName { get; set; }
    
        [DataMember()]
        public string UserID { get; set; }
    
        [DataMember()]
        public string Division { get; set; }
    
        [DataMember()]
        public string Phone { get; set; }
    
        [DataMember()]
        public string Pager { get; set; }
    
        [DataMember()]
        public string CellPhone { get; set; }
    
        [DataMember()]
        public string EMail { get; set; }
    
        [DataMember()]
        public bool Active { get; set; }
    
        [DataMember()]
        public bool Guard { get; set; }
    
    }
    
}
