//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from the DTO.tt T4 template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [DataContract(IsReference=true)]
    public partial class LocationDTO
    {
        
        public LocationDTO()
        {
            this.CampusLocations = new List<CampusLocationDTO>();
            this.LocationHistories = new List<LocationHistoryDTO>();
            this.LogVisitors = new List<LogVisitorDTO>();
        }
    
    
        [DataMember()]
        public int ID { get; set; }
    
        [DataMember()]
        public string Name { get; set; }
    
        [DataMember()]
        public string CreatedByUserID { get; set; }
    
        [DataMember()]
        public System.DateTime CreatedDate { get; set; }
    
        [DataMember()]
        public string ModifiedByUserID { get; set; }
    
        [DataMember()]
        public System.DateTime ModifiedDate { get; set; }
    
        [DataMember()]
        public int Floor { get; set; }
    
        [DataMember()]
        public string Room { get; set; }
    
        [DataMember()]
        public string Phone { get; set; }
    
        [DataMember()]
        public bool IsActive { get; set; }
    
        #region [Navigation Properties]
    
        [DataMember()]
        public List<CampusLocationDTO> CampusLocations { get; set; }
    
        [DataMember()]
        public List<LocationHistoryDTO> LocationHistories { get; set; }
    
        [DataMember()]
        public List<LogVisitorDTO> LogVisitors { get; set; }
                
        #endregion [Navigation Properties]
    
    }
    
}
