//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from the Entity.tt T4 template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [DataContract(IsReference=true)]
    public partial class VisitorLogEntity
    {
        
        public VisitorLogEntity()
        {
            this.VisitorFiles = new List<VisitorFileEntity>();
            this.VisitorLogAccessIDs = new List<VisitorLogAccessIDEntity>();
            this.VisitorLogRoomIDs = new List<VisitorLogRoomIDEntity>();
        }
    
    
        [DataMember()]
        public int VisitID { get; set; }
    
        [DataMember()]
        public string VisitorLogNo { get; set; }
    
        [DataMember()]
        public string FY { get; set; }
    
        [DataMember()]
        public Nullable<byte> StatusId { get; set; }
    
        [DataMember()]
        public Nullable<byte> Amendment { get; set; }
    
        [DataMember()]
        public Nullable<System.DateTime> AmendDateTime { get; set; }
    
        [DataMember()]
        public System.DateTime StartDateTime { get; set; }
    
        [DataMember()]
        public System.DateTime EndDate { get; set; }
    
        [DataMember()]
        public Nullable<bool> OnGoing { get; set; }
    
        [DataMember()]
        public string Company { get; set; }
    
        [DataMember()]
        public byte CampusID { get; set; }
    
        [DataMember()]
        public string OtherRoomInfo { get; set; }
    
        [DataMember()]
        public string OtherAccessAreaInfo { get; set; }
    
        [DataMember()]
        public Nullable<int> PrimaryContactId { get; set; }
    
        [DataMember()]
        public Nullable<int> SecondaryContactId { get; set; }
    
        [DataMember()]
        public string Reason { get; set; }
    
        [DataMember()]
        public string SpecialInstruction { get; set; }
    
        [DataMember()]
        public Nullable<int> SubmittedById { get; set; }
    
        [DataMember()]
        public Nullable<int> DistributedById { get; set; }
    
        [DataMember()]
        public Nullable<int> CreatedById { get; set; }
    
        [DataMember()]
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [DataMember()]
        public Nullable<int> ModifiedById { get; set; }
    
        [DataMember()]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [DataMember()]
        public string Testing { get; set; }
    
        #region [Navigation Properties]
    
        [DataMember()]
        public VisitorEntity Visitor { get; set; }
    
        [DataMember()]
        public List<VisitorFileEntity> VisitorFiles { get; set; }
    
        [DataMember()]
        public List<VisitorLogAccessIDEntity> VisitorLogAccessIDs { get; set; }
    
        [DataMember()]
        public List<VisitorLogRoomIDEntity> VisitorLogRoomIDs { get; set; }
                
        #endregion [Navigation Properties]
    
    }
    
}
