//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from the Entity.tt T4 template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [DataContract(IsReference=true)]
    public partial class VisitorLogRoomIDEntity
    {
    
        [DataMember()]
        public int VisitID { get; set; }
    
        [DataMember()]
        public short RoomID { get; set; }
    
        [DataMember()]
        public string OtherRoom { get; set; }
    
        #region [Navigation Properties]
    
        [DataMember()]
        public RoomEntity Room { get; set; }
    
        [DataMember()]
        public VisitorLogEntity VisitorLog { get; set; }
                
        #endregion [Navigation Properties]
    
    }
    
}
