//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from the Entity.tt T4 template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//  Author: Henry Rodriguez
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [DataContract(IsReference=true)]
    public partial class VisitorEntity
    {
    
        [DataMember()]
        public int VisitID { get; set; }
    
        [DataMember()]
        public Nullable<byte> VisitorNo { get; set; }
    
        [DataMember()]
        public string Visitor1 { get; set; }
    
        [DataMember()]
        public Nullable<int> SecuredAreaId { get; set; }
    
        [DataMember()]
        public Nullable<int> TenantDepartmentId { get; set; }
    
        [DataMember()]
        public Nullable<int> TypeId { get; set; }
    
        #region [Navigation Properties]
    
        [DataMember()]
        public VisitorLogEntity VisitorLog { get; set; }
                
        #endregion [Navigation Properties]
    
    }
    
}
